### PR TITLE
new extension "Advanced Player Links" added

### PR DESCRIPTION
**Pull request by Mik4sa**
Migrated the plugin "Advanced Player Links" into the core

### CODE REVIEW

**Comment by brainfoolong** [comment]
Thank you, i'll merge it but i must do some optimizations here.

**Comment by Mik4sa** [comment]
What kind of optimizations?
I would like to know so that I can consider this for the next time.

**Comment by brainfoolong** [comment]
I will make them right now and will commit it in one commit so you can easily see the changes. I'll inform you here.

What i will change
1. Just one option for all. The "playerlinks" option enable all links. Have an option for each single link is a bit too much.
2. Use of template literals and re-use html code by using a function to reduce code length and improve readability. We have ES6 support, so it's and advantage when we can use it.
3. Keep the same schema for `gf.domchange.events`. You've override the original object `gf.domchange.events = {};`. It should kept as is and adding that later (as every other event also do).

But that are all things that are not really "false". It's just for code consistency and readability in the project.

**Comment by brainfoolong** [comment]
Here we go: https://github.com/brainfoolong/greaterfield/commit/3760b051a6466aa43724fa274c2fd3d0e141cea6

**Pull request merged**
