### PR TITLE
Added an editorconfig file

### PR DESCRIPTION
**Pull request by dpeukert**
More details here: http://editorconfig.org/

### CODE REVIEW

**Comment by brainfoolong** [comment]
Fine, does this follow PSR2 Standard, i guess yes but not sure with editorconfig. Greaterfield is written with PSR2 code standard.

**Comment by brainfoolong** [comment]
Perfect, merged.

**Comment by dpeukert** [comment]
It mostly was, except for the line endings.

**Comment by dpeukert** [comment]
:+1:

**Pull request merged**
